### PR TITLE
Add support for debian 9.13

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description

This pull request:
* Pulls in upstream changes
* Adds explicit support for Debian 9.13

## 💭 Motivation and Context

* Pulling in upstream changes allows this repo to fall under the aegis of lineage
* Debian 9 must be supported until Cyhy is ported to Python3

## 🧪 Testing

All pre-commit hooks and molecule tests pass.

## 🚥 Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (causes existing functionality to change)

## ✅ Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by dav3r — APPROVED** [review]
image

**Review by mcdonnnj — APPROVED** [review]
:shipit:

**Comment by jsf9k** [comment]
@dav3r is that a cylon from the new Battlestar Galactica?

**Comment by dav3r** [comment]
> @dav3r is that a cylon from the new Battlestar Galactica?

Indeed it is!  Though "new" is relative at this point.

**Pull request merged**
